### ISSUE TITLE
Turn off italic

### ISSUE THREAD

**Issue by TmLev** [Yazeed1s/minimal.nvim#3]
Hey! Thanks for the colorscheme.

Is there a way to turn off italic text? I saw some settings [here](https://github.com/Yazeed1s/minimal.nvim/blob/6051c2232de16f88e0ea30395a72de2547823773/lua/minimal-base16/config.lua#L17) and tried to adjust them accordingly:

```lua
local g = vim.g
g.italic_keywords = false
vim.cmd([[colorscheme minimal-base16]])
```

But text is still italic.

**Comment by yazeed1s** [comment]
Hey @TmLev

Thanks for bringing this to my attention, the font I am using does not support italics at all so I did not actually consider adding the options to disable or enable them (to the TS variables). However, now the options are added and the `README.md` is updated accordingly. Please go ahead and update the plugin then you should be able to turn off italics. 

You can use these commands 
```
-- Example config in lua
vim.g.minimal_italic_functions = true
vim.g.minimal_italic_comments = false
-- Load the colorscheme
vim.cmd [[colorscheme minimal]]
-- or 
vim.cmd [[colorscheme minimal-base16]]
```

**Comment by TmLev** [comment]
Hi @Yazeed1s!

Yep, it works now, thank you!
